modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "unigui"
version = "${version}"
displayName = "UniGUI"
authors = "Sixik"
description = '''

'''
#logoFile = ""

[[dependencies.unigui]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.unigui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

