architectury {
    platformSetupLoomIde()
    fabric()
}

sourceSets {
    main {
        java.srcDir "src/main/java-${versionProject.minecraft_version}"
    }
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    uniguiMod {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom uniguiMod
    runtimeClasspath.extendsFrom uniguiMod
    developmentFabric.extendsFrom uniguiMod
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${versionProject.fabric_loader_version}"

    common(project(path: "${versionProject.path}:common", configuration: 'namedElements')) { transitive false }
    uniguiMod(project(path: "${versionProject.path}:fabric", configuration: 'namedElements')) { transitive false }
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'fabric_loader', versionProject.fabric_loader_version
    inputs.property 'minecraft', versionProject.fabric_minecraft_dependency
    inputs.property 'java', versionProject.java_version

    filesMatching('fabric.mod.json') {
        expand version: project.version,
                fabric_loader: versionProject.fabric_loader_version,
                minecraft: versionProject.fabric_minecraft_dependency,
                java: versionProject.java_version
    }
}
